version: "3"
services:
  redis:
    image: redis:alpine   
    ports:
      - "6379:6379"
    restart: always

  redis_app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: always
    volumes:
      - .:/app 

    working_dir: /app
    command: ["mix", "phx.server"]
