version: "3"
services:
  redis:
    image: redis:alpine   # Используем легкий образ Redis
    ports:
      - "6379:6379"
    restart: always

  redis_app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: always
    volumes:
      - .:/app  # Это подходит для разработки, не забудьте убрать для продакшн

    # Лучше настроить рабочую директорию и команду для более гибкой работы
    working_dir: /app
    command: ["mix", "phx.server"]
